services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-price_app
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    networks:
      - crypto-price

  webserver:
    image: nginx:alpine
    container_name: crypto-price_webserver
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - crypto-price

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    container_name: crypto-price_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crypto_price
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - crypto-price

networks:
  crypto-price:
    driver: bridge

volumes:
  dbdata:
    driver: local
